# Generated by Django 3.0.7 on 2020-06-20 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('poster', models.ImageField(default='default_movie.jpg', upload_to='covers')),
                ('genre', models.CharField(blank=True, max_length=64, null=True)),
                ('producer', models.CharField(blank=True, max_length=64, null=True)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('budget', models.PositiveIntegerField(default=0, help_text='in dollars')),
            ],
        ),
    ]
